const styles = {
    container: {
        position: 'relative',
        width: '100%',
        height: '100vh',
        backgroundColor: '#F5E6D3',
        fontFamily: 'Georgia, serif',
    },
    mapContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 0,
    },
    perspectiveIndicator: {
        position: 'absolute',
        top: '16px',
        left: '16px',
    },
    timelineControls: {
        position: 'absolute',
        bottom: '24px',
        left: '50%',
        transform: 'translateX(-50%)',
        width: '80%',
        maxWidth: '800px',
    },
    timeline: {
        height: '4px',
        backgroundColor: 'rgba(92, 64, 51, 0.3)',
        borderRadius: '2px',
        position: 'relative',
        marginBottom: '20px',
        cursor: 'pointer',
    },
    timelineProgress: {
        height: '100%',
        backgroundColor: '#5C4033',
        borderRadius: '2px',
        transition: 'width 0.3s ease',
    },
    timelineMarker: {
        position: 'absolute',
        top: '-4px',
        width: '12px',
        height: '12px',
        backgroundColor: '#8B0000',
        borderRadius: '50%',
        border: '2px solid #F5E6D3',
        transform: 'translateX(-50%)',
    },
    yearDisplay: {
        fontSize: '48px',
        fontWeight: 'bold',
        color: '#3E2A1F',
        marginBottom: '8px',
        textAlign: 'center',
    },
    playControls: {
        display: 'flex',
        justifyContent: 'center',
        gap: '16px',
    },
    controlButton: {
        padding: '8px 16px',
        backgroundColor: '#5C4033',
        color: '#F5E6D3',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        fontSize: '16px',
        transition: 'background-color 0.3s',
    },
    eventPanel: {
        position: 'absolute',
        top: '16px',
        right: '16px',
        width: '300px',
        maxHeight: '60vh',
        overflowY: 'auto',
    },
    eventItem: {
        marginBottom: '12px',
        cursor: 'pointer',
    },
    contributionModal: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(60, 40, 20, 0.4)',
        zIndex: 100,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '16px',
    },
    contributionCard: {
        maxWidth: '500px',
        width: '100%',
    },
};

export {styles}